aws_region             = "eu-north-1"
ami_id                 = "ami-01fd6fa49060e89a6"  # Ubuntu 22.04 LTS for eu-north-1
instance_type          = "t3.medium"
key_name               = "hng13"  # CHANGE THIS to your AWS key pair name
private_key_path       = "~/.ssh/hng13.pem"  # CHANGE THIS to match your key name
ssh_user               = "ubuntu"
ansible_inventory_path = "../../ansible/inventory.ini"
ansible_playbook_path  = "../../ansible/playbook.yml"
server_name            = "micro_service_server"